### ISSUE TITLE
Dúvida Referente app.config ? 

### ISSUE THREAD

**Issue by paulohenry14** [hgmauri/RegistroBoletoOnlineBradesco#1]
Boa tarde, hgmauri.

   Exemplo muito bom, código bem identado e bem comentado. 
Gostaria da sua ajuda referente o significado ImpressaoDigitalCertificadoHomologacao localizado no app.config. Acredito que seja algum chave do certificado certo ? Como consigo ?

Desde já agradeço pela ajuda.

Atenciosamente,
Paulo Henrique

**Comment by hgmauri** [comment]
Fala Paulo Henrique, beleza?

Que bom que gostou, o propósito do código é ajudar a galera.

Sobre o código no app.config, ele é o código do seu certificado do tipo
A1(Até onde sei, esse certificado vc deve comprar) instalado em sua
máquina, ou seja, pra você utilizar esse exemplo, antes você deve modificar
no app.config colocando o código ThumPrint do seu certificado.

Qualquer dúvida me fala que vou ajustando o código pra ficar mais fácil de
entender.



Em 4 de out de 2017 18:01, "paulohenry14" <notifications@github.com>
escreveu:

Boa tarde, hgmauri.

Exemplo muito bom, código bem identado e bem comentado.
Gostaria da sua ajuda referente o significado
ImpressaoDigitalCertificadoHomologacao
localizado no app.config. Acredito que seja algum chave do certificado
certo ? Como consigo ?

Desde já agradeço pela ajuda.

Atenciosamente,
Paulo Henrique

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hgmauri/RegistroBoletoOnlineBradesco/issues/1>, or mute
the thread

**Comment by paulohenry14** [comment]
Beleza, mesmo utilizando o thumbprint do certificado A1, já instalado na máquina ele retorna  privatecert igual nulo ? Saberia me dizer o motivo ?

**Comment by hgmauri** [comment]
Paulo Henrique

Você deve verificar se o certificado está instalado em seu computador primeiro. Siga este link: https://stackoverflow.com/questions/12106011/system-security-cryptography-cryptographicexception-keyset-does-not-exist

Depois você deve pegar o numero de identificação do seu certificado e colocar no app.config (sem espaços)

![image](https://user-images.githubusercontent.com/4854710/31276922-c9c0069e-aa74-11e7-8b0a-0655bd3798b7.png)
